// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ThriveWell.API.Data;

#nullable disable

namespace ThriveWell.API.Migrations
{
    [DbContext(typeof(ThriveWellDbContext))]
    [Migration("20241207230427_updatedUID")]
    partial class updatedUID
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ThriveWell.API.Models.DailyJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Entry")
                        .HasColumnType("text");

                    b.Property<double?>("SeverityAverage")
                        .HasColumnType("double precision");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DailyJournals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2024, 11, 1),
                            Entry = "Feeling pretty rough today. My joints are aching more than usual, especially in my knees and wrists. I’m also feeling fatigued, like I haven’t had enough sleep even though I did rest well. I had a mild headache earlier, but it faded after I drank some water. The pain is worse in the morning, but it gets a little better in the afternoon. Still, I’m not sure I have the energy to do much. Trying to take it easy today.",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2024, 11, 2),
                            Entry = "Woke up feeling surprisingly better today. The joint pain is still there, but it’s more manageable. My energy levels seem higher, so I managed to get some housework done. My stomach was a little upset this morning, but I think it was just from the stress of yesterday. I didn’t have any headaches today, and I even went for a short walk outside. I feel optimistic, hoping this trend continues.",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2024, 11, 3),
                            Entry = "Worse than yesterday. My joints are stiff and swollen this morning, and my energy is back to zero. Even simple tasks like getting dressed felt like a challenge. I had a mild fever in the afternoon, and I ended up resting for most of the day. I’m feeling a bit down, honestly. I’m trying to stay hydrated and eat well, but it’s hard to focus on much. Hoping tomorrow’s better.",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2024, 11, 4),
                            Entry = "A bit of an improvement today. I still have joint pain, but it’s more of a dull ache rather than sharp discomfort. My energy came back in the afternoon, and I was able to cook dinner without feeling exhausted. No headaches, which is a relief. The only real symptom lingering is some light brain fog. I’m hoping it’ll clear up soon. I’m trying to stay active without overdoing it.",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2024, 11, 5),
                            Entry = "The morning started off okay, but by late afternoon, I felt completely wiped out. My muscles are sore, and I’ve had a persistent headache all day. I had to take a nap, which helped a bit, but I’m still drained. I’m frustrated because I was doing so much better a couple of days ago. My stomach feels a little off too. I’m trying not to panic, but it’s hard not to worry when things swing like this.",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateOnly(2024, 11, 6),
                            Entry = "Better day today, thankfully. The pain in my joints is almost gone, and I have more energy than I’ve had all week. I was able to get out of the house for a few errands, and it felt nice to feel “normal” for a change. No headache or nausea, and my mood is improved too. I’m keeping my fingers crossed that this is a sign of recovery. I’ll take it easy tonight, though, just in case.",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateOnly(2024, 11, 8),
                            Entry = "A setback today. I woke up with swollen hands and feet, and my fatigue hit hard early. I feel like I can’t get comfortable, no matter what I do. I had a minor flare-up of muscle pain, and I just want to lie down. I’m frustrated and wondering if something triggered this. Trying not to spiral, but it’s tough. I’ll be more mindful of my diet and hydration tomorrow.",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateOnly(2024, 11, 9),
                            Entry = "A much-needed reprieve today. My joints feel almost normal again, and I’ve got some energy. I even went for a short walk, which I haven’t been able to do in days. I had a little bit of brain fog this morning, but it cleared up by mid-afternoon. I’ve been trying to stick to my routine with medication and diet, so I’m relieved to see some improvement. I feel hopeful but cautious.",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateOnly(2024, 11, 10),
                            Entry = "Not great today. I woke up feeling stiff and had a headache by midday. My muscles are sore, and I can’t seem to shake the fatigue. It’s a bit of a struggle to focus on work. I’m going to rest as much as possible, but I’m getting frustrated with the unpredictability of it all. I’m not sure what’s triggering these fluctuations. I’m trying to stay positive, but it’s hard.",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateOnly(2024, 11, 12),
                            Entry = "A mixed day. The morning was okay—no new flare-ups or unusual pain—but by the afternoon, I started feeling achy again. My stomach’s been a bit off, and I’m worried that might be affecting how I’m feeling. I took a few breaks throughout the day to rest, but my energy levels still feel low. I’m hoping a good night’s sleep will help reset things. Trying not to let the ups and downs get to me too much.",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateOnly(2024, 11, 1),
                            Entry = "Feeling kind of off today. I woke up with a sore throat, which is odd for me. It’s not like a cold—more like something is inflamed in there. I also noticed some swelling in my hands and ankles this morning, which worries me. It’s been a while since I’ve had any swelling like that, so I’m taking it easy. My energy is really low, and I’ve been trying to rest as much as I can, but I’m still exhausted. I don’t know if I should be concerned yet or just wait it out. Hoping it’s nothing serious.",
                            Uid = "KJHKBdskdaksjde9458v"
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateOnly(2024, 11, 2),
                            Entry = "The swelling is worse today, and now I’m having trouble moving my fingers without pain. It’s frustrating, especially since I had plans to get some work done. I’ve been feeling really nauseous off and on as well, which is new. My throat is still sore, but not as much as yesterday. I’m trying to stay hydrated and keep my stress levels down, but it’s hard when my body feels like it’s in revolt. I have an appointment with my doctor tomorrow, so I’m hoping they can give me some clarity.",
                            Uid = "KJHKBdskdaksjde9458v"
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateOnly(2024, 11, 3),
                            Entry = "Doctor's appointment went well, though they weren’t sure what triggered this flare-up. I was given a corticosteroid for the inflammation, and it’s already helping with the swelling in my hands. I still feel a little off—nausea hasn’t completely gone away, and I’m tired—but at least I’m seeing some improvement. My doctor mentioned it might take a few more days to feel fully back to normal. I’m grateful for the medication, but I don’t want to rely on it too much. For now, I’m focusing on getting better, one step at a time.",
                            Uid = "KJHKBdskdaksjde9458v"
                        });
                });

            modelBuilder.Entity("ThriveWell.API.Models.Symptom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Symptoms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Joint Pain",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fatigue",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Swelling",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Headache",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Brain Fog",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Muscle Pain",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Nausea",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Fever",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Stomach Upset",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Sore Throat",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Swelling",
                            Uid = "KJHKBdskdaksjde9458v"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Fatigue",
                            Uid = "KJHKBdskdaksjde9458v"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Nausea",
                            Uid = "KJHKBdskdaksjde9458v"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Headache",
                            Uid = "KJHKBdskdaksjde9458v"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Sore Throat",
                            Uid = "KJHKBdskdaksjde9458v"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Brain Fog",
                            Uid = "KJHKBdskdaksjde9458v"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Muscle Pain",
                            Uid = "KJHKBdskdaksjde9458v"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Stomach Upset",
                            Uid = "KJHKBdskdaksjde9458v"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Fever",
                            Uid = "KJHKBdskdaksjde9458v"
                        });
                });

            modelBuilder.Entity("ThriveWell.API.Models.SymptomLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("SymptomId")
                        .HasColumnType("integer");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SymptomId");

                    b.ToTable("SymptomLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2024, 11, 1),
                            Severity = 3,
                            SymptomId = 1,
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2024, 11, 1),
                            Severity = 4,
                            SymptomId = 2,
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2024, 11, 2),
                            Severity = 2,
                            SymptomId = 1,
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2024, 11, 2),
                            Severity = 3,
                            SymptomId = 3,
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2024, 11, 3),
                            Severity = 4,
                            SymptomId = 6,
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateOnly(2024, 11, 3),
                            Severity = 3,
                            SymptomId = 4,
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateOnly(2024, 11, 4),
                            Severity = 2,
                            SymptomId = 5,
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateOnly(2024, 11, 4),
                            Severity = 1,
                            SymptomId = 7,
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateOnly(2024, 11, 5),
                            Severity = 3,
                            SymptomId = 1,
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateOnly(2024, 11, 5),
                            Severity = 3,
                            SymptomId = 2,
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateOnly(2024, 11, 6),
                            Severity = 2,
                            SymptomId = 4,
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateOnly(2024, 11, 6),
                            Severity = 1,
                            SymptomId = 3,
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateOnly(2024, 11, 8),
                            Severity = 2,
                            SymptomId = 8,
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateOnly(2024, 11, 8),
                            Severity = 4,
                            SymptomId = 2,
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateOnly(2024, 11, 9),
                            Severity = 1,
                            SymptomId = 1,
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateOnly(2024, 11, 9),
                            Severity = 3,
                            SymptomId = 5,
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateOnly(2024, 11, 10),
                            Severity = 4,
                            SymptomId = 6,
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateOnly(2024, 11, 10),
                            Severity = 3,
                            SymptomId = 4,
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateOnly(2024, 11, 12),
                            Severity = 2,
                            SymptomId = 3,
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateOnly(2024, 11, 12),
                            Severity = 3,
                            SymptomId = 7,
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateOnly(2024, 11, 1),
                            Severity = 3,
                            SymptomId = 11,
                            Uid = "KJHKBdskdaksjde9458v"
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateOnly(2024, 11, 2),
                            Severity = 2,
                            SymptomId = 12,
                            Uid = "KJHKBdskdaksjde9458v"
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateOnly(2024, 11, 3),
                            Severity = 4,
                            SymptomId = 13,
                            Uid = "KJHKBdskdaksjde9458v"
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateOnly(2024, 11, 4),
                            Severity = 3,
                            SymptomId = 14,
                            Uid = "KJHKBdskdaksjde9458v"
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateOnly(2024, 11, 5),
                            Severity = 1,
                            SymptomId = 15,
                            Uid = "KJHKBdskdaksjde9458v"
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateOnly(2024, 11, 6),
                            Severity = 2,
                            SymptomId = 16,
                            Uid = "KJHKBdskdaksjde9458v"
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateOnly(2024, 11, 8),
                            Severity = 3,
                            SymptomId = 17,
                            Uid = "KJHKBdskdaksjde9458v"
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateOnly(2024, 11, 9),
                            Severity = 4,
                            SymptomId = 18,
                            Uid = "KJHKBdskdaksjde9458v"
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateOnly(2024, 11, 10),
                            Severity = 2,
                            SymptomId = 19,
                            Uid = "KJHKBdskdaksjde9458v"
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateOnly(2024, 11, 12),
                            Severity = 3,
                            SymptomId = 19,
                            Uid = "KJHKBdskdaksjde9458v"
                        });
                });

            modelBuilder.Entity("ThriveWell.API.Models.SymptomTrigger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SymptomLogId")
                        .HasColumnType("integer");

                    b.Property<int>("SymptomSeverity")
                        .HasColumnType("integer");

                    b.Property<int>("TriggerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SymptomLogId");

                    b.HasIndex("TriggerId");

                    b.ToTable("SymptomTriggers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SymptomLogId = 1,
                            SymptomSeverity = 3,
                            TriggerId = 1
                        },
                        new
                        {
                            Id = 2,
                            SymptomLogId = 2,
                            SymptomSeverity = 2,
                            TriggerId = 6
                        },
                        new
                        {
                            Id = 3,
                            SymptomLogId = 3,
                            SymptomSeverity = 4,
                            TriggerId = 5
                        },
                        new
                        {
                            Id = 4,
                            SymptomLogId = 4,
                            SymptomSeverity = 2,
                            TriggerId = 14
                        },
                        new
                        {
                            Id = 5,
                            SymptomLogId = 5,
                            SymptomSeverity = 3,
                            TriggerId = 4
                        },
                        new
                        {
                            Id = 6,
                            SymptomLogId = 6,
                            SymptomSeverity = 1,
                            TriggerId = 3
                        },
                        new
                        {
                            Id = 7,
                            SymptomLogId = 7,
                            SymptomSeverity = 4,
                            TriggerId = 6
                        },
                        new
                        {
                            Id = 8,
                            SymptomLogId = 8,
                            SymptomSeverity = 2,
                            TriggerId = 2
                        },
                        new
                        {
                            Id = 9,
                            SymptomLogId = 9,
                            SymptomSeverity = 3,
                            TriggerId = 4
                        },
                        new
                        {
                            Id = 10,
                            SymptomLogId = 10,
                            SymptomSeverity = 3,
                            TriggerId = 14
                        },
                        new
                        {
                            Id = 11,
                            SymptomLogId = 11,
                            SymptomSeverity = 1,
                            TriggerId = 13
                        },
                        new
                        {
                            Id = 12,
                            SymptomLogId = 12,
                            SymptomSeverity = 2,
                            TriggerId = 6
                        },
                        new
                        {
                            Id = 13,
                            SymptomLogId = 13,
                            SymptomSeverity = 4,
                            TriggerId = 5
                        },
                        new
                        {
                            Id = 14,
                            SymptomLogId = 14,
                            SymptomSeverity = 3,
                            TriggerId = 8
                        },
                        new
                        {
                            Id = 15,
                            SymptomLogId = 15,
                            SymptomSeverity = 3,
                            TriggerId = 7
                        },
                        new
                        {
                            Id = 16,
                            SymptomLogId = 16,
                            SymptomSeverity = 2,
                            TriggerId = 15
                        },
                        new
                        {
                            Id = 17,
                            SymptomLogId = 17,
                            SymptomSeverity = 4,
                            TriggerId = 6
                        },
                        new
                        {
                            Id = 18,
                            SymptomLogId = 18,
                            SymptomSeverity = 3,
                            TriggerId = 5
                        },
                        new
                        {
                            Id = 19,
                            SymptomLogId = 19,
                            SymptomSeverity = 2,
                            TriggerId = 14
                        },
                        new
                        {
                            Id = 20,
                            SymptomLogId = 20,
                            SymptomSeverity = 3,
                            TriggerId = 1
                        },
                        new
                        {
                            Id = 21,
                            SymptomLogId = 21,
                            SymptomSeverity = 3,
                            TriggerId = 16
                        },
                        new
                        {
                            Id = 22,
                            SymptomLogId = 22,
                            SymptomSeverity = 2,
                            TriggerId = 17
                        },
                        new
                        {
                            Id = 23,
                            SymptomLogId = 23,
                            SymptomSeverity = 4,
                            TriggerId = 19
                        },
                        new
                        {
                            Id = 24,
                            SymptomLogId = 24,
                            SymptomSeverity = 3,
                            TriggerId = 18
                        },
                        new
                        {
                            Id = 25,
                            SymptomLogId = 25,
                            SymptomSeverity = 1,
                            TriggerId = 20
                        },
                        new
                        {
                            Id = 26,
                            SymptomLogId = 26,
                            SymptomSeverity = 2,
                            TriggerId = 16
                        },
                        new
                        {
                            Id = 27,
                            SymptomLogId = 27,
                            SymptomSeverity = 3,
                            TriggerId = 19
                        },
                        new
                        {
                            Id = 28,
                            SymptomLogId = 28,
                            SymptomSeverity = 4,
                            TriggerId = 18
                        },
                        new
                        {
                            Id = 29,
                            SymptomLogId = 29,
                            SymptomSeverity = 2,
                            TriggerId = 20
                        },
                        new
                        {
                            Id = 30,
                            SymptomLogId = 30,
                            SymptomSeverity = 3,
                            TriggerId = 16
                        });
                });

            modelBuilder.Entity("ThriveWell.API.Models.Trigger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Triggers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cold Weather",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hot Weather",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lack of Sleep",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Overexertion",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Infection/Illness",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Stress",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Physical Injury",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Flu Vaccination",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Hormonal Changes",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Cold Weather",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Gluten",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Dairy",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Nightshades: Tomatoes, Eggplant, Peppers",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Dehydration",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Caffeine",
                            Uid = "6tLAOsxFS8e7Jq2bh2s2g6jUXnv2"
                        },
                        new
                        {
                            Id = 16,
                            Name = "New Laundry Detergent",
                            Uid = "KJHKBdskdaksjde9458v"
                        },
                        new
                        {
                            Id = 17,
                            Name = "New Lotion/Skincare Products",
                            Uid = "KJHKBdskdaksjde9458v"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Lack of Exercise",
                            Uid = "KJHKBdskdaksjde9458v"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Smoking",
                            Uid = "KJHKBdskdaksjde9458v"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Alcohol Consumption",
                            Uid = "KJHKBdskdaksjde9458v"
                        });
                });

            modelBuilder.Entity("ThriveWell.API.Models.SymptomLog", b =>
                {
                    b.HasOne("ThriveWell.API.Models.Symptom", "Symptom")
                        .WithMany()
                        .HasForeignKey("SymptomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Symptom");
                });

            modelBuilder.Entity("ThriveWell.API.Models.SymptomTrigger", b =>
                {
                    b.HasOne("ThriveWell.API.Models.SymptomLog", "SymptomLog")
                        .WithMany("SymptomTrigger")
                        .HasForeignKey("SymptomLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThriveWell.API.Models.Trigger", "Trigger")
                        .WithMany()
                        .HasForeignKey("TriggerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SymptomLog");

                    b.Navigation("Trigger");
                });

            modelBuilder.Entity("ThriveWell.API.Models.SymptomLog", b =>
                {
                    b.Navigation("SymptomTrigger");
                });
#pragma warning restore 612, 618
        }
    }
}
